version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - crossws
  - defu
  - demi
  - formkit
  - guiiai
  - intlify
  - listhen
  - logg
  - ofetch
  - unhead
  - unocss
  - unplugin
  - vueuse
ignoreWords: []
import: []
