kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 30101
        protocol: TCP
      - containerPort: 8081
        hostPort: 30102
        protocol: TCP
      - containerPort: 8082
        hostPort: 30103
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 30201
        protocol: TCP
      - containerPort: 8081
        hostPort: 30202
        protocol: TCP
      - containerPort: 8082
        hostPort: 30203
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 30301
        protocol: TCP
      - containerPort: 8081
        hostPort: 30302
        protocol: TCP
      - containerPort: 8082
        hostPort: 30303
        protocol: TCP
