kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30101
        hostPort: 8080
        protocol: TCP
      - containerPort: 30102
        hostPort: 8081
        protocol: TCP
      - containerPort: 30103
        hostPort: 8082
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 30201
        hostPort: 8180
        protocol: TCP
      - containerPort: 30202
        hostPort: 8181
        protocol: TCP
      - containerPort: 30203
        hostPort: 8182
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 30301
        hostPort: 8280
        protocol: TCP
      - containerPort: 30302
        hostPort: 8281
        protocol: TCP
      - containerPort: 30303
        hostPort: 8282
        protocol: TCP
