apiVersion: streaming-audio.ayaka.io/v1alpha1
kind: VoiceModel
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: test
spec:
  podTemplate:
    spec:
      containers:
        - name: worker-container
          image: test.nekomeowww.local/streaming-audio/inference-server:0.0.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: "1000M"
              nvidia.com/gpu: "1"
            requests:
              cpu: "500m"
              memory: "500M"
              nvidia.com/gpu: "1"
