# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to streaming-audio.sizigistudios.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: voicemodel-viewer-role
rules:
- apiGroups:
  - streaming-audio.sizigistudios.com
  resources:
  - voicemodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streaming-audio.sizigistudios.com
  resources:
  - voicemodels/status
  verbs:
  - get
