apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
  labels:
    app: inference-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inference-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      containers:
        - name: worker-container
          image: test.sizigi.local/streaming-audio/inference-server:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "200M"
              nvidia.com/gpu: "1"
            requests:
              cpu: "500m"
              memory: "100M"
              nvidia.com/gpu: "1"
