/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioAnalyser: typeof import('./components/AudioAnalyser.vue')['default']
    AudioVisualizer: typeof import('./components/AudioVisualizer.vue')['default']
    AudioVisualizerBars: typeof import('./components/AudioVisualizerBars.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./components/Screen.vue')['default']
  }
}
